/*#
  * @file Order.scala
  * @begin 8-Apr-2015
  * @author <a href="mailto:giuseppe.greco@gokillo.com">Giuseppe Greco</a>
  * @copyright 2015 <a href="http://gokillo.com">Gokillo</a>
  */

package models.pay.api

import com.wordnik.swagger.annotations._
import org.joda.time.DateTime
import models.common.api.{Status, RefId}
import models.auth.IdentityMode._
import models.pay.OrderType._

/**
  * Defines the `Order` schema for Swagger.
  */
@ApiModel(value = "Order", description = "Represents an order for receiving or sending coins")
trait Order {

  @ApiModelProperty(value = "The identifier of the order", dataType = "string", /* readOnly = true, */ position = 1)
  def id: Option[String]
  @ApiModelProperty(value = "The identifier of the parent order", dataType = "string", /* readOnly = true, */ position = 2)
  def parentId: Option[String]
  @ApiModelProperty(value = "The identifier of a possible order generated by an external system this order is associated with", dataType = "string", /* readOnly = true, */ position = 3)
  def peerId: Option[String]
  @ApiModelProperty(value = "The identifier of the account that issued the order", dataType = "string", /* readOnly = true, */ position = 4)
  def accountId: Option[String]
  @ApiModelProperty(value = "A reference to the object associated with the order", dataType = "RefId", /* readOnly = true, */ position = 5)
  def refId: Option[RefId]
  @ApiModelProperty(value = "The order type", dataType = "string", /* readOnly = true, */ position = 6)
  def orderType: Option[OrderType]
  @ApiModelProperty(value = "The identity mode of the order issuer", dataType = "IdentityMode", /* readOnly = true, */ position = 7)
  def issuerIdentityMode: Option[IdentityMode]
  @ApiModelProperty(value = "The receiving or sending coin address", dataType = "string", /* readOnly = true, */ position = 8)
  def coinAddress: Option[String]
  @ApiModelProperty(value = "The amount of the order", dataType = "Coin", /* readOnly = true, */ position = 9)
  def amount: Option[Coin]
  @ApiModelProperty(value = "The status of the order", dataType = "string", /* readOnly = true, */ position = 10)
  def status: Option[Status]
  @ApiModelProperty(value = "The time the order was created, in ISO 8601 format", dataType = "datetime", /* readOnly = true, */ position = 11)
  def creationTime: Option[DateTime]
}
